[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.150.0"     # pin a current Extended version
  HUGO_ENV = "production"

# Optional: make Deploy Previews noindex
[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "all"

[context.deploy-preview]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
